/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package OTHELLO;

import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Insets;
import javafx.util.Pair;
import javax.swing.JPanel;
import javax.swing.border.Border;

public class OTHELLOGUI extends javax.swing.JFrame {

    /**
     * Creates new form OTHELLOGUI
     */
    int[][] board;
    Coordinate topLeft;
    int size;   //the dimension of each cell
    boolean humanTurn;
    Pair clickedCell;   //contains the row and column number of the clicked cell
    
   
    
    public OTHELLOGUI(int[][] board) {
        this.board=board;
        topLeft=new Coordinate(30,30);
        size=30;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new BoardPanel(this);
        turnLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel.setBackground(new java.awt.Color(254, 250, 247));
        panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelMouseClicked(evt);
            }
        });

        turnLabel.setText("Your Turn");

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(turnLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(418, 418, 418))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addGap(0, 424, Short.MAX_VALUE)
                .addComponent(turnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
            .addComponent(panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void setLabelText(String msg)    {
        this.turnLabel.setText(msg);
    }
    public void setBoard(int[][] b) {
        this.board=b;
        this.repaint();
    }
    private void panelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMouseClicked
        // TODO add your handling code here:
        int x=evt.getX();
        int y = evt.getY();
        int xx=x-topLeft.x;
        int yy=y-topLeft.y;
        x-=topLeft.x;
        y-=topLeft.y;
        x/=size+10;
        y/=size+10;
        //System.out.println("mouse pressed... "+x+" "+y+" evt: "+xx+" "+yy);
        if(humanTurn)   {
            clickedCell = new Pair<>(y,x);
            humanTurn=false;
        }
        panel.repaint();
        this.repaint();
    }//GEN-LAST:event_panelMouseClicked
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel panel;
    private javax.swing.JLabel turnLabel;
    // End of variables declaration//GEN-END:variables
}

class Coordinate 
{
    int x,y;
    Coordinate()    {x=0;y=0;}
    Coordinate(int x,int y){this.x=x;this.y=y;}
}

class BoardPanel extends JPanel
{
    OTHELLOGUI fg;
    public BoardPanel(OTHELLOGUI fg) {
        super();
        this.fg=fg;
    }
    
    @Override
    protected void paintComponent(Graphics g) {
        
        super.paintComponent(g); //To change body of generated methods, choose Tools | Templates.
        
        this.setPreferredSize(new Dimension(800,800));
        Coordinate topLeft=fg.topLeft;
        
        int[][] board=fg.board;
        
        int height = board.length;
        int width = board[0].length;
//        System.out.println("h: "+height+" w: "+width);
        int size=fg.size;
        
        for(int r=0,j=topLeft.y; r<=height; j+=size+10,r++) {
            g.setColor(Color.BLACK);
            g.fillRoundRect(topLeft.x, j, width*(10+size), 5, 2000, 2000);
//            System.out.println("iii: "+j);
            for(int c=0,i=topLeft.x; c<=width; c++,i+=size+10)  {
                g.setColor(Color.BLUE);
                g.fillRoundRect(i,topLeft.y,5, height*(size+10), 2000,2000);
                if(r>=height || c>=width)   continue;
                if(board[r][c]>0)  {
                    g.setColor(new Color(42,255,42));
                    g.fillOval(i+5, j+5, size,size);
//                    System.out.println("drawing circle in "+i+" "+j);
                }
                else if(board[r][c]<0)    {
                    g.setColor(new Color(218,255,32));
                    g.fillOval(i+5, j+5, size,size);
                }
            }
        }
    
}
   
}